### ISSUE TITLE
I cant change the listen and send port 

### ISSUE THREAD

**Issue by sat62010** [ALLATRA-IT/srt-server#3]
Hi 
I tried to change the listen port from 9000 to 2000 ,but the server doesn't accept another port than 9000.
I have changed the port from the main.cpp file as below .
  service_rcv = string("9000");
    service_snd = string("9001");

     to
  service_rcv = string("2000");
    service_snd = string("2001");

but the server doesn't accept the 2000 port or any port than 9000.

Thanks.

**Comment by amukhsimov** [comment]
> Hi
> I tried to change the listen port from 9000 to 2000 ,but the server doesn't accept another port than 9000.
> I have changed the port from the main.cpp file as below .
> service_rcv = string("9000");
> service_snd = string("9001");
> 
> ```
>  to
> ```
> 
> service_rcv = string("2000");
> service_snd = string("2001");
> 
> but the server doesn't accept the 2000 port or any port than 9000.
> 
> Thanks.

Hi! 
```
service_rcv = string("9000");
service_snd = string("9001");  // Default values
```
These are just default values, if arguments are passed via command line, the default values will be overwritten, if you want to run srt-server on different ports, you can pass them as arguments, or, if you want to change default values, ensure running srt-server without any arguments.

**Comment by sat62010** [comment]
Hi! ,
Thanks for your reply, it worked when I changed the default values to different ports . 
can I run the server with multi ports  instead of one port ? for example can I make listen ports as 1000 and 2000 at the same time ?
also how I enable the server to run in the background ? I have tried to run it as systemctl start srt-server but I get error message says cant find srt-server .
Thank you.

**Comment by amukhsimov** [comment]
> Hi! ,
> Thanks for your reply, it worked when I changed the default values to different ports .
> can I run the server with multi ports instead of one port ? for example can I make listen ports as 1000 and 2000 at the same time ?
Hi again! By now, srt-server doesn't support this feature, if you want it to listen on different ports, you can start multiple instances, for example 1000->1001 and 2000->2001.

> also how I enable the server to run in the background ? I have tried to run it as systemctl start srt-server but I get error message says cant find srt-server .
> Thank you.
If you want to run srt-server in background, there are many ways achieving it:
 - Create systemd daemon (here are simple instructions: https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6)
 - You can run srt-server detached in command line: srt-server &
 - Run detached in command line and hide the output: srt-server >/dev/null &
 - You can use tmux. A friend of mine adviced me using tmux (https://tmuxcheatsheet.com/) it is something like command line session manager.

**Comment by sat62010** [comment]
Hi again,
Thanks for your replay .
it worked with tmux and srt-server & 
but it didn't work with systemctl . I crated fie as bellow
/etc/systemd/system/srt-server


Unit]
Description=srt-server
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
User=ubuntu
ExecStart=/usr/local/bin/srt-server

[Install]
WantedBy=multi-user.target

I get error says can't find srt-server for (systemctl start srt-server)

can you please email me at  sat62010@gmail.com

Thank you
